### ISSUE TITLE
Support meta config

### ISSUE THREAD

**Issue by argonui** [argonui/TTSModManager#51]
If there was such a file as `TTSModManager.config`, then it could allow for setting more options and flag than makes sense to have on the commandline.

Some ideas:
* paths to ... (instead of current default)
  * lua src ($moddir/src)
  * xml src ($moddir/xml)
  * root config ($moddir/config.json)
* write to src when decomposing?
* set $moddir instead of passing each time
* set $modfile instead of passing each time

Please comment with other ideas and what use cases this would enable

**Comment by rolandostar** [comment]
Having a config will enable cross-team workflows by providing a consistent configuration which can be stored in Git as part of onboarding, my personal preference would be for the config file to be `yaml` which has package integration with Go ([link](https://pkg.go.dev/gopkg.in/yaml.v2)). 

I'm picturing something like:

`TTSModManager.config.yaml`
```yaml
---
paths:
  lua:
  - "./src"
  - "./other_src"
  - C:/Absolute/Path/Also
  xml:
  - "./xml"
  - "./other_src"
  - C:/Absolute/Path/Also
root_config: "./config.json"
moddir: C:/Some/Absolute/Path
modfile: "./output.json"
reverse: false
writesrc: true
```
(Paths being array to have multiple places to look for)


You could even have different configs for different purposes and call them by changing `TTSModManager.exe --config X` or `Y`

There's also the issue of where will this file be looked for, personally I think it should go from local to global. Something like, CMD flag overrides all, then look for it first next to the binary (`./`) and finally a static dir maybe in `~/.TTSModManager`
 
I think this could be better handled by something like [Configure](https://github.com/gravitational/configure) which includes environment variable support
